# fly.toml app configuration file generated for filmes-bot-felipe on 2026-08-02T14:40:34-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'filmes-bot-felipe'
primary_region = 'gru'

[build]

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
